### ISSUE TITLE
script1006 expected ')' ie11

### ISSUE THREAD

**Issue by ops1ops** [blakeembrey/change-case#73] opened 2019-12-05 15:02 UTC
crashes in ie 11 
![Screenshot from 2019-12-05 18-07-20](https://user-images.githubusercontent.com/49243022/70247376-52c83680-178a-11ea-91cf-63850c24f345.png)

**Comment by blakeembrey** [comment] 2019-12-05 18:16
Thanks for the flag. This is because the code being emitted was designed for ES2015. Let me target ES5 instead, but if you have time it'd be good to have tests for this.

**Comment by blakeembrey** [comment] 2019-12-06 03:04
Fixed with https://github.com/blakeembrey/change-case/commit/10c83d7634d9afc82f8be25715ae09412d1846c6.

**Closed by blakeembrey** 2019-12-06 03:04 UTC
Labels: enhancement
