### ISSUE TITLE
sentenceCase function replaces non-English alphabets with whitespace

### ISSUE THREAD

**Issue by judgegodwins** [blakeembrey/change-case#280] opened 2022-02-05 15:19 UTC
`sentenceCase` replaces non-English alphabets with whitespace:

E.g `sentenceCase('itinéraire')` returns 'Itin raire'.

**Comment by blakeembrey** [comment] 2022-02-06 00:51
Closing as a duplicate of https://github.com/blakeembrey/change-case/issues/152.

**Closed by blakeembrey** 2022-02-06 00:51 UTC
