### ISSUE TITLE
Snake case underscore before numbers

### ISSUE THREAD

**Issue by ghost** [blakeembrey/change-case#50] opened 2018-09-14 06:01 UTC
At the moment, snakeCase doesn't insert an underscore before numbers. I would expect it to do that.

Current behaviour:
`changeCase.snakeCase("pricePer100Km")` returns `price_per100_km`.

Expected behaviour:
`changeCase.snakeCase("pricePer100Km")` returns `price_per_100_km`.

If this is not a bug, then I would suggest making it an option through a possible argument. Maybe like this:

`changeCase.snakeCase("pricePer100Km", {handleNumbers: true})` returns `price_per_100_km`.

**Comment by blakeembrey** [comment] 2018-09-15 01:57
The problem is that `Per100` is highly ambiguous. It's not clear those are two different words in camel case. Happy to accept a PR to add the option. For example, there's a similar option to merge numbers in https://github.com/blakeembrey/camel-case.

**Comment by jonlambert** [comment] 2019-06-09 13:24
Any chance of this getting merged? I'm looking for a solution which can correctly split apart numbers from camel case strings like this.

**Comment by blakeembrey** [comment] 2019-07-10 04:18
@jonlambert I'd recommend opening a PR first, but aiming to do a refactor with these requests this month.

**Comment by moltar** [comment] 2020-04-30 12:36
FYI lodash's snake case does the right thing with numbers.

**Comment by blakeembrey** [comment] 2020-05-02 05:55
The "right thing" can be subjective, e.g. `TestV1`. Happy to change the default, but it's hard to get consensus and it'll inevitably upset someone. For context, I'm sure this package originally worked the way you suggest but it likely change in response to a bug report.

**Comment by aayush123** [comment] 2021-05-16 13:12
@blakeembrey I created a PR with the new option. However, I did have to copy the default Split Regex.
Would it be better if we exported the default regex from nocase and extend the array in this package?
I believe it would allow better maintainability in future.

**Comment by blakeembrey** [comment] 2021-05-19 02:32
> Would it be better if we exported the default regex from nocase and extend the array in this package?

Yeah, that makes sense to me. Since it's a pretty global option, do you want to just have it as a configuration for the base `no-case` package which all other packages can pass along?

**Comment by moltar** [comment] 2021-05-19 02:39
> FYI lodash's snake case does the right thing with numbers.

Just ran into a case where it doesn't make sense: hex strings.

**Closed** 2023-09-26 18:20 UTC
Labels: enhancement
