### ISSUE TITLE
Turkish character problem 

### ISSUE THREAD

**Issue by Byblack36** [blakeembrey/change-case#297] opened 2023-06-08 12:05 UTC
The letter "I" solve the problem I am having how big the Turkish character problem I return the letter "I" is small "l" when it turns

**Comment by blakeembrey** [comment] 2023-06-09 00:17
Can you share what the expected character is? Those are all just ascii characters using either I or L and I'm unclear what you're expecting. Which package are you having problems with?

**Comment by blakeembrey** [comment] 2023-06-09 18:05
As an example, `'I'.toLocaleLowerCase('tr')` returns `ı`. I assume that's correct?

**Comment by Byblack36** [comment] 2023-06-09 19:19
Example = IĞDIR
Output= iğdir
Should Be= ığdır

**Comment by blakeembrey** [comment] 2023-06-09 19:46
What package are you using?

**Comment by blakeembrey** [comment] 2023-06-09 19:48
I think the issue is that I haven’t exposed the locale setting outside the lower/upper case packages. I can look into doing that in the next major release.

**Comment by Byblack36** [comment] 2023-06-09 19:51
![image](https://github.com/blakeembrey/change-case/assets/44087037/0ff36c55-d571-4aed-8c6b-fd95e1305560)

**Comment by Byblack36** [comment] 2023-06-09 19:53
> I think the problem is the locale setting small/big letters on the outside of the package that I didn't show it. I can think of to do this in the next major release.

would be great if you update

**Comment by blakeembrey** [comment] 2023-06-10 05:27
Currently there’s no internationalization support in the library but I will update it when I have time. Which method of the library are you using?

**Comment by Byblack36** [comment] 2023-06-10 17:21
I don't quite understand what you said, are you asking for what purpose I used it?

**Comment by blakeembrey** [comment] 2023-09-30 01:52
This has been fixed with `change-case@5.0.0`. Please update and let me know if you still see any issues.

**Closed by blakeembrey** 2023-09-30 01:52 UTC
