### ISSUE TITLE
Title case not being implemented when the string is a property of an object.

### ISSUE THREAD

**Issue by tazzzzzzz** [blakeembrey/change-case#98] opened 2020-05-02 03:50 UTC
The titleCase function doesn't seem to be working on strings who are stored as properties of an object, for some reason.

```var { titleCase } = require("title-case")
user = {
    name : "nAME"
}
const text = user.name
console.log(titleCase(text)); //Output displayed on console is "nAME", as opposed to "Name"
```
Note: 
```console.log(titleCase(user.name))``` also produces the output ```nAME```

**Comment by blakeembrey** [comment] 2020-05-02 04:48
Duplicate of https://github.com/blakeembrey/change-case/issues/99. This isn't how `titleCase` works.

**Closed by blakeembrey** 2020-05-02 04:48 UTC
