### ISSUE TITLE
BUG: `snakecase('_id')` => `id`

### ISSUE THREAD

**Issue by grimen** [blakeembrey/change-case#77] opened 2019-12-27 21:24 UTC
This is a bug for sure, this is not the expected output for snake casing.

**Comment by blakeembrey** [comment] 2019-12-27 21:30
I'm unable to replicate with the latest version: https://runkit.com/blakeembrey/5e0677c07d4082001a02850f.

**Comment by blakeembrey** [comment] 2019-12-27 21:31
Closing since `id` is expected behavior based on the title change. This is how it's always worked: https://github.com/blakeembrey/change-case/issues/50.

**Closed by blakeembrey** 2019-12-27 21:31 UTC

**Comment by grimen** [comment] 2019-12-30 01:29
My point of renaming the title: It is a bug that always existed, but I had a workaround for it.

The correct implementation of snake case for `_<something>` is:

```python
Python 3.8.0 (default, Dec 29 2019, 20:15:26) 
[Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import stringcase
>>> stringcase.snakecase('_')
'_'
>>> stringcase.snakecase('_foo')
'_foo'
>>> 
```

**Comment by blakeembrey** [comment] 2019-12-30 17:52
It's a reasonable request. I'd always suggest searching and commenting on an existing open issue though. As a maintainer, I'll usually close out duplicate issues. As for implementing this feature, I think it should be fairly easy to do - but should `camelCase` and `PascalCase` also follow the convention? It's pretty standard to do underscore prefix on them too.

**Comment by blakeembrey** [comment] 2019-12-30 17:56
One idea is to support a `prefix: '_'` option globally, and use the prefix when this code executes: https://github.com/blakeembrey/change-case/blob/1c1377a692d328ae01221b2a1532bade38e1eaa3/packages/no-case/src/index.ts#L36-L37. Would that suit your needs, or do you expect this to be the default behavior?

**Comment by grimen** [comment] 2020-01-02 03:09
Yes an optional override is probably the way to go to avoid breaking changes for any existing projects.

I did some experiments with similar libraries in various languages and noticed there seems to be a common inconsistency, e.g. in most popular **Ruby** (`activesupport`) and **Python** (`stringcase`) libraries `_<something>` keeps the prefix, but in Sublime Text package **Case Conversion** it is stripped.
